package cminor.messages.errors.syntax;

import cminor.messages.errors.Error;
import cminor.messages.errors.scope.ScopeError;
import cminor.utilities.PrettyPrint;

/**
 * An {@link Error} generated by the {@link cminor.parser.Parser}.
 * @author Daniel Levy
 */
public class SyntaxError extends Error {

    protected String location;

    /**
     * {@inheritDoc}
     */
    @Override
    protected String buildMessageHeader(String fileName) {
        return super.buildMessageHeader(fileName)
                + PrettyPrint.RED
                + "Syntax Error "
                + messageNumber()
                + ": ";
    }

    @Override
    public void createMessage(String fileName) {
        msg = buildMessageHeader(fileName) + buildMainMessage() + PrettyPrint.RESET + location + "\n";
    }

    /**
     * {@inheritDoc}
     */
    public SyntaxError asSyntaxError() { return this; }
}
