package cminor.messages.errors.syntax;

import cminor.messages.errors.Error;
import cminor.utilities.PrettyPrint;

/**
 * An {@link Error} generated by the {@link parser.Parser}.
 * @author Daniel Levy
 */
public class SyntaxError extends Error {

    /**
     * {@inheritDoc}
     */
    @Override
    protected String buildMessageHeader(String fileName) {
        return super.buildMessageHeader(fileName)
                + PrettyPrint.CYAN
                + "Syntax Error "
                + messageNumber()
                + "\n\n"
                + PrettyPrint.RESET;
    }
}
