package messages.errors.runtime;

import messages.errors.Error;
import utilities.PrettyPrint;

/**
 * An {@link Error} generated by the {@link interpreter.Interpreter}.
 * @author Daniel Levy
 */
public class RuntimeError extends Error {

    /**
     * {@inheritDoc}
     */
    @Override
    protected String buildMessageHeader(String fileName) {
        return super.buildMessageHeader(fileName)
                + PrettyPrint.RED
                + "Runtime Error "
                + errorNumber()
                + "\n\n"
                + PrettyPrint.RESET;
    }
}
