package cminor.messages.errors.mod;

import cminor.messages.errors.Error;
import cminor.utilities.PrettyPrint;

/**
 * An {@link Error} that is generated by the {@link modifierchecker.ModifierChecker}.
 * @author Daniel Levy
 */
public class ModError extends Error {

    /**
     * {@inheritDoc}
     */
    @Override
    protected String buildMessageHeader(String fileName) {
        return super.buildMessageHeader(fileName)
                + PrettyPrint.YELLOW
                + "Modifier Error "
                + messageNumber()
                + "\n\n"
                + PrettyPrint.RESET;
    }
}
