package cminor.messages.errors.runtime;

import cminor.messages.errors.Error;
import cminor.utilities.PrettyPrint;

/**
 * An {@link Error} generated by the {@link interpreter.Interpreter}.
 * @author Daniel Levy
 */
public class RuntimeError extends Error {

    /**
     * {@inheritDoc}
     */
    @Override
    protected String buildMessageHeader(String fileName) {
        return super.buildMessageHeader(fileName)
                + PrettyPrint.RED
                + "Runtime Error "
                + messageNumber()
                + ": ";
    }
}
