package cminor.messages.errors.type;

import cminor.messages.errors.Error;
import cminor.utilities.PrettyPrint;

/**
 * An {@link Error} generated by the {@link typechecker.TypeChecker}.
 * @author Daniel Levy
 */
public class TypeError extends Error {

    /**
     * {@inheritDoc}
     */
    @Override
    protected String buildMessageHeader(String fileName) {
        return super.buildMessageHeader(fileName)
                + PrettyPrint.GREEN
                + "Type Error "
                + messageNumber()
                + "\n\n"
                + PrettyPrint.RESET;
    }
}
